### ISSUE TITLE
Module Import Fails

### ISSUE THREAD

**Issue by wennebo1** [techservicesillinois/SecOps-PowerShell-DMI#33] opened 2020-06-02 15:09 UTC
Using PowerShell Core v7.0.1 on Windows 10, I am unable to import this module. When I attempt to run `Install-Module UofIDMI` (through PSGallery), I receive hundreds of errors with the text
![2020-06-02 10_10_29-Administrator_ PowerShell 7 (x64)](https://user-images.githubusercontent.com/19394542/83536905-7eb64180-a4b9-11ea-81fc-4e6e79da5dd0.png)

I have attempted to uninstall the UofIDMI module, as well as the PSSQLite module, then reinstalling again to no avail.

**Comment by MKletz** [comment] 2020-06-02 21:09
@wennebo1 you'll need to update PSSQlite to 1.1, You unfortunately cannot specify a minimum version for a dependency. Looks like you have 1.0.3 from the screen shot.

**Comment by MKletz** [comment] 2020-06-02 21:20
I may actually have identified a way to prevent the error but you can get around it for now by updating PSSQLite from the gallery

**Comment by MKletz** [comment] 2020-06-04 20:23
Confirmed resolved in the above PR

**Closed by MKletz** 2020-06-04 20:23 UTC
